#!/usr/bin/env bash
# install/lib-manifest.sh — file-hash + commit metadata, manifest read/write,
# generate_manifest_for_existing.
#
# Requires: lib-logging.sh, REPO_ROOT global, and the MANIFEST_ENTRIES
# (indexed array) + INSTALLED_AGENTS_LIST (indexed array) globals.

[ -n "${LIB_AGENTS_MANIFEST_LOADED:-}" ] && return 0
LIB_AGENTS_MANIFEST_LOADED=1

# ============================================================================
# Cross-platform SHA-256 hash utility
# ============================================================================
compute_hash() {
  local file="$1"
  if [ ! -f "$file" ]; then
    echo "MISSING"
    return
  fi
  if command -v shasum &>/dev/null; then
    shasum -a 256 "$file" | cut -d' ' -f1
  elif command -v sha256sum &>/dev/null; then
    sha256sum "$file" | cut -d' ' -f1
  else
    err "No SHA-256 tool found (need shasum or sha256sum)"
    exit 1
  fi
}

# ============================================================================
# Source commit tracking
# ============================================================================
SOURCE_COMMIT=""

get_source_commit() {
  if [ -n "${SOURCE_COMMIT:-}" ]; then
    echo "$SOURCE_COMMIT"
    return
  fi
  git -C "${REPO_ROOT}" rev-parse HEAD 2>/dev/null || echo "unknown"
}

# ============================================================================
# Manifest infrastructure
# ============================================================================
declare -a MANIFEST_ENTRIES=()
declare -a INSTALLED_AGENTS_LIST=()

# Record a file installation into the manifest entries array
record_file() {
  local dest_path="$1"
  local tier="$2"
  local hash
  hash=$(compute_hash "$dest_path")
  MANIFEST_ENTRIES+=("[${tier}] ${dest_path} sha256=${hash}")
}

# Write the manifest lockfile
write_manifest() {
  local target="$1"
  local manifest_path="${target}/.lib-agents.lock"
  local source_commit
  source_commit=$(get_source_commit)
  local installed_at
  installed_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date +"%Y-%m-%dT%H:%M:%SZ")
  local agents_csv
  agents_csv=$(printf '%s,' "${INSTALLED_AGENTS_LIST[@]}" | sed 's/,$//')

  # If manifest already exists, merge with existing entries
  if [ -f "$manifest_path" ]; then
    local existing_agents=""
    existing_agents=$(grep "^installed_agents=" "$manifest_path" 2>/dev/null | cut -d'=' -f2- || true)
    if [ -n "$existing_agents" ]; then
      # Merge agent lists (union)
      local merged_agents="$existing_agents,$agents_csv"
      agents_csv=$(echo "$merged_agents" | tr ',' '\n' | sort -u | tr '\n' ',' | sed 's/,$//')
    fi

    # Merge file entries: keep existing entries not in new entries
    local -a merged_entries=()
    local -A new_paths=()
    for entry in "${MANIFEST_ENTRIES[@]}"; do
      local path
      path=$(echo "$entry" | sed 's/^\[[a-z]*\] //' | sed 's/ sha256=.*//')
      new_paths["$path"]=1
      merged_entries+=("$entry")
    done
    # Add existing entries whose paths are not in the new set
    while IFS= read -r line || [ -n "$line" ]; do
      [[ -z "$line" ]] && continue
      [[ "$line" != \[* ]] && continue
      local existing_path
      existing_path=$(echo "$line" | sed 's/^\[[a-z]*\] //' | sed 's/ sha256=.*//')
      if [ -z "${new_paths[$existing_path]+x}" ]; then
        merged_entries+=("$line")
      fi
    done < <(grep '^\[' "$manifest_path" 2>/dev/null || true)
    MANIFEST_ENTRIES=("${merged_entries[@]}")
  fi

  # Write manifest atomically via temp file
  local tmp_manifest="${manifest_path}.tmp"
  {
    echo "# lib-agents manifest lockfile"
    echo "# Auto-generated by install.sh — do not edit manually"
    echo "source_commit=${source_commit}"
    echo "source_url=${REPO_URL}"
    echo "installed_at=${installed_at}"
    echo "installed_agents=${agents_csv}"
    if [ -n "${PROFILE_NAME:-}" ]; then
      echo "profile=${PROFILE_NAME}"
    fi
    if [ "${USE_LINK:-}" = "link" ]; then
      echo "mode=link"
    else
      echo "mode=copy"
    fi
    echo ""
    # Sort entries by tier then path
    printf '%s\n' "${MANIFEST_ENTRIES[@]}" | sort
  } > "$tmp_manifest"
  mv "$tmp_manifest" "$manifest_path"
  ok "Manifest written to ${manifest_path}"
}

# Read an existing manifest into associative arrays
# Sets: MANIFEST_HASHES[path]=hash, MANIFEST_TIERS[path]=tier, MANIFEST_COMMIT, MANIFEST_URL, MANIFEST_AT, MANIFEST_AGENTS_CSV, MANIFEST_MODE
declare -A MANIFEST_HASHES=()
declare -A MANIFEST_TIERS=()
MANIFEST_COMMIT=""
MANIFEST_URL=""
MANIFEST_AT=""
MANIFEST_AGENTS_CSV=""
MANIFEST_MODE=""
MANIFEST_PROFILE=""

read_manifest() {
  local manifest_path="$1"
  MANIFEST_HASHES=()
  MANIFEST_TIERS=()
  MANIFEST_COMMIT=""
  MANIFEST_URL=""
  MANIFEST_AT=""
  MANIFEST_AGENTS_CSV=""
  MANIFEST_MODE=""
  MANIFEST_PROFILE=""

  if [ ! -f "$manifest_path" ]; then
    return 1
  fi

  while IFS= read -r line || [ -n "$line" ]; do
    # Skip comments and empty lines
    [[ -z "$line" ]] && continue
    [[ "$line" == \#* ]] && continue

    # Parse header fields
    case "$line" in
      source_commit=*)
        MANIFEST_COMMIT="${line#source_commit=}"
        ;;
      source_url=*)
        MANIFEST_URL="${line#source_url=}"
        ;;
      installed_at=*)
        MANIFEST_AT="${line#installed_at=}"
        ;;
      installed_agents=*)
        MANIFEST_AGENTS_CSV="${line#installed_agents=}"
        ;;
      mode=*)
        MANIFEST_MODE="${line#mode=}"
        ;;
      profile=*)
        MANIFEST_PROFILE="${line#profile=}"
        ;;
      \[*)
        # Parse file entry: [tier] path sha256=hash
        local tier path hash
        tier=$(echo "$line" | sed 's/^\[\([a-z]*\)\].*/\1/')
        path=$(echo "$line" | sed 's/^\[[a-z]*\] //' | sed 's/ sha256=.*//')
        hash=$(echo "$line" | sed 's/.*sha256=//')
        MANIFEST_HASHES["$path"]="$hash"
        MANIFEST_TIERS["$path"]="$tier"
        ;;
    esac
  done < "$manifest_path"
  return 0
}

# Generate a manifest for an existing installation (migration path)
generate_manifest_for_existing() {
  local target="$1"
  local project_root="$2"

  info "No manifest found. Generating manifest for existing installation..."
  MANIFEST_ENTRIES=()
  INSTALLED_AGENTS_LIST=()

  # Scan agent definitions
  if [ -d "${target}/agents" ]; then
    for f in "${target}/agents"/*.md; do
      [ -f "$f" ] || continue
      local agent_name
      agent_name=$(basename "$f" .md)
      INSTALLED_AGENTS_LIST+=("$agent_name")
      record_file "$f" "agent"
    done
  fi

  # Scan tools
  if [ -d "${target}/tools" ]; then
    for f in "${target}/tools"/*.ts; do
      [ -f "$f" ] || continue
      record_file "$f" "shared"
    done
  fi

  # Scan commands
  if [ -d "${target}/commands" ]; then
    for f in "${target}/commands"/*.md; do
      [ -f "$f" ] || continue
      record_file "$f" "shared"
    done
  fi

  # Scan skills
  if [ -d "${target}/skills" ]; then
    for skill_dir in "${target}/skills"/*/; do
      [ -d "$skill_dir" ] || continue
      if [ -f "${skill_dir}/SKILL.md" ]; then
        record_file "${skill_dir}/SKILL.md" "shared"
      fi
    done
  fi

  # Scan prompts
  if [ -d "${target}/prompts" ]; then
    for f in "${target}/prompts"/*.md; do
      [ -f "$f" ] || continue
      record_file "$f" "shared"
    done
  fi

  # Scan user-tier root files
  for root_file in AGENTS.md; do
    if [ -f "${project_root}/${root_file}" ]; then
      record_file "${project_root}/${root_file}" "user"
    fi
  done
  if [ -f "${target}/package.json" ]; then
    record_file "${target}/package.json" "user"
  fi

  # Write manifest with migration markers
  local manifest_path="${target}/.lib-agents.lock"
  local installed_at
  installed_at=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date +"%Y-%m-%dT%H:%M:%SZ")
  local agents_csv
  agents_csv=$(printf '%s,' "${INSTALLED_AGENTS_LIST[@]}" | sed 's/,$//')

  local tmp_manifest="${manifest_path}.tmp"
  {
    echo "# lib-agents manifest lockfile"
    echo "# Auto-generated by install.sh — do not edit manually"
    echo "source_commit=unknown (migrated)"
    echo "source_url=${REPO_URL}"
    echo "installed_at=${installed_at} (migrated)"
    echo "installed_agents=${agents_csv}"
    echo "mode=copy"
    echo ""
    printf '%s\n' "${MANIFEST_ENTRIES[@]}" | sort
  } > "$tmp_manifest"
  mv "$tmp_manifest" "$manifest_path"
  ok "Generated manifest for existing installation (migrated)"
  info "Run '--status' to review tracked files."
}

